# Generated by Django 5.1.2 on 2024-10-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('bca', 'BCA'), ('bit', 'BIT')], default='bca', max_length=50),
        ),
    ]
