# Generated by Django 5.1.2 on 2024-11-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_contact_number_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='department',
            field=models.CharField(choices=[('', 'Select'), ('bca', 'BCA'), ('bit', 'BIT')], default='bca', max_length=10),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='department',
            field=models.CharField(choices=[('', 'Select'), ('bca', 'BCA'), ('bit', 'BIT')], default='bca', max_length=10),
        ),
    ]
