# Generated by Django 5.1.2 on 2024-11-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
