# Generated by Django 5.1.2 on 2024-10-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seller_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('second_hand', 'Second_Hand')], default='new', max_length=20),
        ),
    ]
