# Generated by Django 5.1.2 on 2024-10-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='username',
            field=models.CharField(default='seller', max_length=50),
        ),
    ]
