# Generated by Django 5.1.2 on 2024-10-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
