# Generated by Django 5.1.2 on 2024-11-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_number'),
        ('core', '0005_delete_cart'),
    ]

    operations = [
    ]
