# Generated by Django 5.1.2 on 2024-10-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_seller_user_seller_groups_seller_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_permissions',
        ),
    ]
